# API related configuration.
api:
  # The port to listen for the incoming requests.
  # Default: 8080
  port: 8080
  # Matchers is the service that subscriptions depends on
  matchers:
    uri: matchers:8080
# Database related configuration.
db:
  # Database connection URI.
  uri: mongodb+srv://localhost/?retryWrites=true&w=majority
  # Database name to use.
  name: subscriptions-staging
  table:
    # Database table name to use.
    name: subscriptions
