apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "subscriptions.fullname" . }}
  labels:
    {{- include "subscriptions.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "subscriptions.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "subscriptions.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "subscriptions.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: API_PORT
              value: "{{ .Values.service.port }}"
            - name: DB_URI
              value: "{{ .Values.db.protocol }}://{{ .Release.Name }}-{{ .Values.db.hostname }}/?retryWrites=true&w=majority"
            - name: DB_NAME
              value: {{ .Values.db.name }}
            - name: DB_USERNAME
              value: {{ .Values.db.username }}
            {{- if .Values.db.password.secret.enabled }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name}}-{{ .Values.db.password.secret.name }}"
                  key: "{{ .Values.db.password.secret.key }}"
            {{- else }}
            - name: DB_PASSWORD
              value: "{{ .Values.db.password.raw }}"
            {{- end }}
            - name: DB_TABLE_NAME
              value: {{ .Values.db.table.name }}
            - name: API_KIWI_TREE_COMPLETE_URI
              value: "{{ .Release.Name}}-{{ .Values.api.uri.kiwi.tree.complete }}"
            - name: API_KIWI_TREE_PARTIAL_URI
              value: "{{ .Release.Name}}-{{ .Values.api.uri.kiwi.tree.partial }}"
            - name: LOG_LEVEL
              value: "{{ .Values.log.level }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            grpc:
              port: {{ .Values.service.port }}
          readinessProbe:
            grpc:
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
