apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "subscriptions.fullname" . }}
  labels:
    {{- include "subscriptions.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "subscriptions.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "subscriptions.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "subscriptions.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: API_PORT
              value: "{{ .Values.service.port }}"
            - name: API_HTTP_PORT
              value: "{{ .Values.service.http.port }}"
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.db.secret.name }}"
                  key: "{{ .Values.db.secret.keys.url }}"
            - name: DB_NAME
              value: {{ .Values.db.name }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.db.secret.name }}"
                  key: "{{ .Values.db.secret.keys.username }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.db.secret.name }}"
                  key: "{{ .Values.db.secret.keys.password }}"
            - name: DB_TABLE_NAME
              value: {{ .Values.db.table.name }}
            - name: DB_TABLE_SHARD
              value: "{{ .Values.db.table.shard }}"
            - name: DB_TLS_ENABLED
              value: "{{ .Values.db.tls.enabled }}"
            - name: DB_TLS_INSECURE
              value: "{{ .Values.db.tls.insecure }}"
            - name: LOG_LEVEL
              value: "{{ .Values.log.level }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.http.port }}
              protocol: TCP
          livenessProbe:
            grpc:
              port: {{ .Values.service.port }}
          readinessProbe:
            grpc:
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
