apiVersion: v1
kind: Service
metadata:
  name: {{ include "subscriptions.fullname" . }}
  labels:
    {{- include "subscriptions.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: grpc
  selector:
    {{- include "subscriptions.selectorLabels" . | nindent 4 }}
